### ISSUE TITLE
Page seems to be outdated when loaded from cache

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-web-repo#21]
Some Browsers pre-cache our page. Therefore it seems to be outdated when displayed. The user has to manually refresh the page to see the actual state of our mirrors. Maybe a forced refresh when loading the page the first time might help ...

**Comment by Huluti** [comment]
We could use an htaccess file on the root folder. Like this: http://www.ipserverone.info/programming/how-to-prevent-http-file-caching-with-htaccess/. What do you think?

**Comment by Huluti** [comment]
Should be fixed by c558f29f211e5e3441e48b02703af3ca1d09ea0b.

**Comment by Huluti** [comment]
It doesn't... so best solution is to use the .htaccess file.

**Comment by philmmanjaro** [comment]
I applied it now. Let's check if it works now ...

**Comment by philmmanjaro** [comment]
Hmm, seems still not be working. Maybe we should readd the refresh button and click it once the page has sorted the list once.

**Comment by Huluti** [comment]
I'll add this to the javascript: `location.reload(true);`

**Comment by Huluti** [comment]
Should be really fixed by 7b98e69dd4ae8647ed482de2b6c59570c576577b.

**Comment by philmmanjaro** [comment]
Hmm, I don't understand it. We have now the latest code on our server and still the cache problem in **palemoon**. @Huluti: did you test it with other browsers? Is it specific to some?

**Comment by Huluti** [comment]
I've [said here](https://github.com/manjaro/manjaro-web-repo/commit/7b98e69dd4ae8647ed482de2b6c59570c576577b#commitcomment-20970965) that it doesn't work. I haven't find the best solution. What is our web server, Apache or Nginx ?

**Comment by Huluti** [comment]
The cache is managed by the server and it seems that this is the policy of the servers Manjaro. If the server is on Apache, then the .htaccess must be ignored by the server configuration.

**Comment by fhdk** [comment]
> .htaccess must be ignored by the server configuration

I was of that conception that the virtualservers .htaccess overrides httpd.conf but the setting must be enabled in httpd.conf for .htaccess to actually honor the setting

**Comment by philmmanjaro** [comment]
Adopted as Ticket# 86123
